# Generated by Django 4.2.2 on 2023-06-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='other_charges',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='total_fare',
        ),
    ]
