# Generated by Django 4.2.2 on 2023-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_ticket_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='business_fare',
            new_name='fare',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='economy_fare',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='first_fare',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_class',
        ),
        migrations.AddField(
            model_name='flight',
            name='seats',
            field=models.PositiveIntegerField(default=60, null=True),
        ),
    ]
